name: CI for webapp

on: 
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REGION: "us-west-2"

jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
    
        - name: Docker version
          run: docker --version

        - run: echo ${{ env.ECR_URL_PYDBCAPSTONE }}