name: Build and push image to ECR

on: 
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_URL: ${{ vars.ECR_URL_PYDBCAPSTONE }}

jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
    
        - name: Connect with ECR
          run: |
            full_url=$ECR_URL
            url_split=(${full_url//./ })
            region=${url_split[3]}
            aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $ECR_URL

        - name: Build image
          run: |
            full_url=$ECR_URL
            url_split=(${full_url//// })
            proj_name=${url_split[1]}
            echo "Run number:" ${{ github.run_number }}
            docker build -t $proj_name:${{ github.run_number }}.0 .

        - name: Add latest tag and push image
          run: |
            docker image ls
