name: Build and push image to ECR

on: 
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_URL: ${{ vars.ECR_URL_PYDBCAPSTONE }}

jobs:

  Build_and_push_image:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Set variables (1)
          run: |
            full_url=$ECR_URL
            url_split=(${full_url//./ })
            echo "REGION=${url_split[3]}" >> "$GITHUB_ENV"
            url_split=(${full_url//// })
            echo "URL_ROOT=${url_split[0]}" >> "$GITHUB_ENV"
            echo "PROJ_NAME=${url_split[1]}" >> "$GITHUB_ENV"
            echo "VERSION=0.${{ github.run_number }}.0" >> "$GITHUB_ENV"

        - name: Set variables (2)
          run: |
            echo "NAME_AND_VERSION_TAG=$PROJ_NAME:$VERSION" >> "$GITHUB_ENV"
            echo "NAME_AND_LATEST_TAG=$URL_ROOT/$PROJ_NAME:latest" >> "$GITHUB_ENV"

        - name: Show variables
          run: |
            echo $REGION
            echo $PROJ_NAME
            echo $URL_ROOT
            echo $VERSION
            echo $NAME_AND_VERSION_TAG
            echo $NAME_AND_LATEST_TAG

        - name: Connect with ECR
          run: |
            aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URL

        - name: Build image
          run: |
            docker build -t $NAME_AND_VERSION_TAG .

        - name: Add latest tag
          run: |
            docker tag $NAME_AND_VERSION_TAG $NAME_AND_LATEST_TAG
            docker image ls

        - name: Push image to ECR
          run :
            docker push $NAME_AND_LATEST_TAG --all-tags